# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
 schedule:
 - cron: "* * * * *"

name: Render DailySystemReport

jobs:
  render:
    name: Render DailySystemReport
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install packages
        run: Rscript -e 'devtools::install_github("SwampThingPaul/AnalystHelper")'
      - name: Install packages
        run: Rscript -e 'install.packages(c("rmarkdown","knitr","rvest","readr","rjson","jsonlite","kableExtra","plyr","reshape","lubridate","dataRetrieval","zoo","RCurl"))'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("DailySystemReport_v2.Rmd")'
      - name: Commit results
        run: |
          git commit README.md -m 'Re-build DailySystemReport_v2.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
